const PHRASES = [
  "Everything is going to be fine",
  "Kis omak",
  "Uh, by the way",
  "Sweety sweety",
  "Hey jacare",
  "Muitas palavras",
  "Oh, that's really cool man",
  "You should go out",
  "Crazy man",
  "Why you did that?",
  "Oh guys this is hurting",
  "I'm so tired man",
  "Fuck you jacare",
  "Halass Halass",
  "It's so hot here man",
  "Oh yeah",
  "Charmuta",
  "Be like a gangster",
  "Filha da puta",
  "Oh my god man",
  "Eu não falo portugues mano",
  "Caralho mano",
  "Muito chata",
  "I'm so sleepy",
  "What the fuck?",
  "Porra caralho",
  "He/she is so fucking rude man",
  "I swear bro",
  "Fucking bitches",
  "Toma de quatro mi casa",
  "Cala boca piranha",
  "Calm down guys",
  "Fuck you mila",
  "Por favor mano",
  "Porra",
  "Sweet is not sweet today",
  "Você é muito gatinha",
  "Você é muito gostosa",
  "I don't know why man",
  "Fala muito mano",
  "Ibn al-kalb",
  "I like you",
  "I like so much man",
  "Calma calabreso",
  "Alguém safado mano",
  "Você é mentiroso mano",
  "Você é gado",
  "Que que isso?",
  "O que falando?",
  "Por que você brava mano?",
  "Halass",
  "Muito legal",
  "Listen listen!",
  "I'm really sad",
  "Hate or love at the same coin",
  "Don't be shy",
  "I'm so honest",
  "That's not good",
  "Batatas"
];
